# syntax=docker/dockerfile:1
FROM ubuntu:jammy

run apt-get update -y ; apt-get install -y gcc make autotools-dev autoconf automake libtool libltdl7 libltdl-dev binutils-dev build-essential devscripts debhelper libcmocka-dev libcmocka0


